### PR TITLE
Add related headers section

### PR DESCRIPTION
**Pull request by RubenVerborgh**

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
@larsgsvensson If you can find the RFC that officially allows such an interpretation, I will link to it (but I don't think it exists).

**Comment by larsgsvensson** [comment]
@RubenVerborgh https://tools.ietf.org/html/rfc6839 ?

**Comment by RubenVerborgh** [comment]
Okay, so there _is_ a spec for it. My bad.
A lot of SHOULD though, and no JSON-LD for instance.

**Comment by RubenVerborgh** [comment]
@larsgsvensson Added this in 5abe8d0b5f19c90b80445476c790f9415b87090e. (BTW this PR will still receive some commits, will ping when done.)

**Comment by RubenVerborgh** [comment]
@larsgsvensson The related headers section is complete, feel free to review and merge.

**Pull request merged**
